version: '3.8'

services:
  claude-dev:
    build: .
    container_name: claude-code-container
    volumes:
      # 現在のディレクトリをコンテナの/workspaceにマウント
      - .:/workspace
      # ホームディレクトリの永続化（設定ファイルなど）
      - claude-home:/home/developer
    environment:
      # AnthropicのAPIキーを環境変数で設定（実際の値は.envファイルまたは手動で設定）
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    working_dir: /workspace
    stdin_open: true
    tty: true
    # ポートフォワーディング（開発サーバーなどで使用）
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8080:8080"

  # 同じボリュームを使用する別のコンテナ
  claude-dev-2:
    build: .
    container_name: claude-code-container-2
    volumes:
      # 同じワークスペースボリューム
      - .:/workspace
      # 同じホームディレクトリボリュームを共有
      - claude-home:/home/developer
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    working_dir: /workspace
    stdin_open: true
    tty: true
    # 異なるポート番号を使用
    ports:
      - "3001:3000"
      - "8001:8000"
      - "8081:8080"

volumes:
  claude-home:
    driver: local 